respostas = {
    "E aí": "E aí, meu velho! Viu o jogo ontem?",
    "E aí, meu velho! Viu o jogo ontem?": "Vi sim mano, que sufoco no segundo tempo kkk",
    "Vi sim mano, que sufoco no segundo tempo kkk": "Nem me fala, quase infartei com aquele gol no final",
    "Nem me fala, quase infartei com aquele gol no final": "O juiz tava doido também, deu umas faltas nada a ver",
    "O juiz tava doido também, deu umas faltas nada a ver": "Clássico é sempre assim, emoção até o último segundo",
    "Clássico é sempre assim, emoção até o último segundo": "Tu acha que a gente chega no G4 esse ano?",
    "Tu acha que a gente chega no G4 esse ano?": "Se continuar jogando assim, dá pra sonhar sim",
    "Se continuar jogando assim, dá pra sonhar sim": "Tem que parar de vacilar fora de casa né",
    "Tem que parar de vacilar fora de casa né": "Verdade... e nosso ataque precisa ser mais eficiente",
    "Verdade... e nosso ataque precisa ser mais eficiente": "Mas também, sem meia armador fica difícil",
    "Mas também, sem meia armador fica difícil": "Pois é, o time sente falta de um camisa 10 de verdade",
    "Pois é, o time sente falta de um camisa 10 de verdade": "Saudades do tempo do Jadson, hein?",
    "Saudades do tempo do Jadson, hein?": "Demais! A bola chegava redonda no pé do atacante",
    "Demais! A bola chegava redonda no pé do atacante": "Hoje em dia é só chutão e rezar 😅",
    "Hoje em dia é só chutão e rezar 😅": "Kkkkk exatamente",
    "Kkkkk exatamente": "Bora assistir o próximo jogo aqui em casa?",
    "Bora assistir o próximo jogo aqui em casa?": "Fechou, leva a cerveja que eu preparo a carne 🍻🔥",
    "Fechou, leva a cerveja que eu preparo a carne 🍻🔥": "Tamo junto, é nóis! ⚽",
    "Tamo junto, é nóis! ⚽": "Aproveitar que o tempo vai estar firme, né? Últimos dias só deu chuva",
    "Aproveitar que o tempo vai estar firme, né? Últimos dias só deu chuva": "Nem me fala... semana passada choveu até dentro do busão kkk",
    "Nem me fala... semana passada choveu até dentro do busão kkk": "Clássico do transporte público, né? E ainda atrasou meu trampo",
    "Clássico do transporte público, né? E ainda atrasou meu trampo": "Falando nisso, como tá lá no serviço? Muito corre?",
    "Falando nisso, como tá lá no serviço? Muito corre?": "Rapaz, tá puxado... mas tô aprendendo coisa nova, pelo menos",
    "Rapaz, tá puxado... mas tô aprendendo coisa nova, pelo menos": "Isso que importa! Melhor do que ficar empacado no mesmo lugar",
    "Isso que importa! Melhor do que ficar empacado no mesmo lugar": "Verdade... e tu, tá trampando de casa ainda?",
    "Verdade... e tu, tá trampando de casa ainda?": "Tô sim, mas confesso que sinto falta de dar aquela escapada pro café kkk",
    "Tô sim, mas confesso que sinto falta de dar aquela escapada pro café kkk": "A resenha da firma faz falta mesmo... mas pelo menos evita trânsito",
    "A resenha da firma faz falta mesmo... mas pelo menos evita trânsito": "Isso é! Ganho pelo menos uma horinha a mais de sono 😴",
    "Isso é! Ganho pelo menos uma horinha a mais de sono 😴": "E com esse monte de app hoje em dia, dá até pra automatizar as tarefas do trampo",
    "E com esse monte de app hoje em dia, dá até pra automatizar as tarefas do trampo": "Sim! Tô usando um bot que organiza meus e-mails sozinho, é uma mão na roda",
    "Sim! Tô usando um bot que organiza meus e-mails sozinho, é uma mão na roda": "Caraca, me manda esse depois! Eu ainda tô na planilha raiz kkk",
    "Caraca, me manda esse depois! Eu ainda tô na planilha raiz kkk": "Nada contra a planilha, mas tem umas IA que fazem milagre hoje",
    "Nada contra a planilha, mas tem umas IA que fazem milagre hoje": "Vi um vídeo de um cara que usa IA até pra responder cliente no WhatsApp",
    "Vi um vídeo de um cara que usa IA até pra responder cliente no WhatsApp": "Já já a gente nem precisa trabalhar mais, só gerenciar os robôs 😂",
    "Já já a gente nem precisa trabalhar mais, só gerenciar os robôs 😂": "Tomara que os robôs não fiquem bravos e virem contra a gente tipo nos filmes",
    "Tomara que os robôs não fiquem bravos e virem contra a gente tipo nos filmes": "Skynet feelings kkkk",
    "Skynet feelings kkkk": "Pior que do jeito que a tecnologia tá avançando, não duvido de mais nada não",
    "Pior que do jeito que a tecnologia tá avançando, não duvido de mais nada não": "Lembra quando a maior revolução era colocar crédito no celular pra mandar SMS? kkk",
    "Lembra quando a maior revolução era colocar crédito no celular pra mandar SMS? kkk": "Ou então esperar dar meia-noite pra usar internet discada sem estourar o pulso da família kkk",
    "Ou então esperar dar meia-noite pra usar internet discada sem estourar o pulso da família kkk": "E aquele barulhinho do modem? Inesquecível",
    "E aquele barulhinho do modem? Inesquecível": "Se tocava o telefone, caía tudo... era guerra em casa 😂",
    "Se tocava o telefone, caía tudo... era guerra em casa 😂": "Hoje em dia a galera nem sabe o que é viver sem Wi-Fi",
    "Hoje em dia a galera nem sabe o que é viver sem Wi-Fi": "Nem isso, mano... tenta explicar o que era Orkut pra alguém de 15 anos hoje",
    "Nem isso, mano... tenta explicar o que era Orkut pra alguém de 15 anos hoje": "E as comunidades? 'Eu odeio acordar cedo' era obrigatória kkk",
    "E as comunidades? 'Eu odeio acordar cedo' era obrigatória kkk": "E o 'depósito de scraps'? Lotado de glitter e gif piscando",
    "E o 'depósito de scraps'? Lotado de glitter e gif piscando": "A internet era um carnaval, mas tinha personalidade 😂",
    "A internet era um carnaval, mas tinha personalidade 😂": "Hoje em dia é só dancinha no TikTok e trend reciclada kkk",
    "Hoje em dia é só dancinha no TikTok e trend reciclada kkk": "Nada contra, mas tem hora que parece tudo igual, né?",
    "Nada contra, mas tem hora que parece tudo igual, né?": "Sim! E quando a gente percebe, já passou 2 horas rolando feed sem ver nada útil",
    "Sim! E quando a gente percebe, já passou 2 horas rolando feed sem ver nada útil": "Mano, esses algoritmos te prendem bonito… parece até hipnose",
    "Mano, esses algoritmos te prendem bonito… parece até hipnose": "E depois fica aquele cansaço mental, como se tivesse feito mil coisas e nada ao mesmo tempo",
    "E depois fica aquele cansaço mental, como se tivesse feito mil coisas e nada ao mesmo tempo": "Tô tentando colocar limite de uso no celular, mas é difícil demais",
    "Tô tentando colocar limite de uso no celular, mas é difícil demais": "O pior é que a gente abre o celular pra ver uma coisa e acaba em 5 apps diferentes",
    "O pior é que a gente abre o celular pra ver uma coisa e acaba em 5 apps diferentes": "Verdade! Tô começando a desligar o Wi-Fi de propósito às vezes",
    "Verdade! Tô começando a desligar o Wi-Fi de propósito às vezes": "Boa tática! Acho que vou aderir também… paz de espírito vem sem notificação",
    "Verdade! Tô começando a desligar o Wi-Fi de propósito às vezes": "Boa tática! Acho que vou aderir também… paz de espírito vem sem notificação",
    "Boa tática! Acho que vou aderir também… paz de espírito vem sem notificação": "Pô, não aguento mais esse monte de notificação do caralho... é grupo, app, tudo apitando ao mesmo tempo",
    "Pô, não aguento mais esse monte de notificação do caralho... é grupo, app, tudo apitando ao mesmo tempo": "Mano, parece que o celular tá possuído às vezes, do nada começa a vibrar que nem louco",
    "Mano, parece que o celular tá possuído às vezes, do nada começa a vibrar que nem louco": "E sempre quando tu tá tentando descansar ou ver um filme, essa porra começa a tocar",
    "E sempre quando tu tá tentando descansar ou ver um filme, essa porra começa a tocar": "Exato! Outro dia eu quase joguei essa merda pela janela",
    "Exato! Outro dia eu quase joguei essa merda pela janela": "Kkkkk mano, é foda... mas aí a gente lembra que pagou caro e dá aquela segurada",
    "Kkkkk mano, é foda... mas aí a gente lembra que pagou caro e dá aquela segurada": "Ô se pagou... celular hoje em dia tá mais caro que carro usado",
    "Ô se pagou... celular hoje em dia tá mais caro que carro usado": "E mesmo assim trava às vezes... vai tomar no cu, viu",
    "E mesmo assim trava às vezes... vai tomar no cu, viu": "É rir pra não chorar... tecnologia do caralho mas parece que veio com prazo de validade",
    "É rir pra não chorar... tecnologia do caralho mas parece que veio com prazo de validade": "Igual impressora: funciona 3 vezes, depois dá pau eterno kkkk",
    "Igual impressora: funciona 3 vezes, depois dá pau eterno kkkk": "Pior merda já inventada, essa desgraça só falta pedir sacrifício pra imprimir um papel"


}